"""initial_schema

Revision ID: 1b78d25381e3
Revises: 
Create Date: 2026-10-09 12:37:37.971685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b78d25381e3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_name', sa.String(length=255), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('total_recipients', sa.Integer(), nullable=False),
    sa.Column('pending_count', sa.Integer(), nullable=False),
    sa.Column('processing_count', sa.Integer(), nullable=False),
    sa.Column('successful_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generation_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generation_jobs_status'), ['status'], unique=False)
        batch_op.create_index('ix_generation_jobs_status_created', ['status', 'created_at'], unique=False)

    op.create_table('certificate_recipients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('recipient_name', sa.String(length=255), nullable=False),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('certificate_id', sa.String(length=36), nullable=True),
    sa.Column('storage_key', sa.String(length=512), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['generation_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('certificate_recipients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certificate_recipients_certificate_id'), ['certificate_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_certificate_recipients_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificate_recipients_status'), ['status'], unique=False)
        batch_op.create_index('ix_recipients_job_status', ['job_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate_recipients', schema=None) as batch_op:
        batch_op.drop_index('ix_recipients_job_status')
        batch_op.drop_index(batch_op.f('ix_certificate_recipients_status'))
        batch_op.drop_index(batch_op.f('ix_certificate_recipients_job_id'))
        batch_op.drop_index(batch_op.f('ix_certificate_recipients_certificate_id'))

    op.drop_table('certificate_recipients')
    with op.batch_alter_table('generation_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_generation_jobs_status_created')
        batch_op.drop_index(batch_op.f('ix_generation_jobs_status'))

    op.drop_table('generation_jobs')
    # ### end Alembic commands ###
